require_relative "../dnsimple"

namespace :emails do
  task :update do
    forwards = EMAILS.inject([]) do |forwards, (from, tos)|
      forwards += tos.map { |to| [from, to] }
    end
    existing_forwards = DNSimple.client.get("email_forwards").map do |hash|
      [hash["email_forward"]["from"].chomp("@outwardbound.hr"), hash["email_forward"]["to"]]
    end
    new_forwards = forwards - existing_forwards

    new_forwards.each do |from, to|
      DNSimple.client.post("email_forwards", email_forward: {from: from, to: to})
    end

    puts "No new forwards" if new_forwards.empty?
  end
end

EMAILS = {
  "aco"                   => ["aleksakocijan@yahoo.com"],
  "aleksa.kocijan"        => ["aco@outwardbound.hr"],
  "apply"                 => ["prijava@outwardbound.hr"],
  "biljana.bekic"         => ["biljana@outwardbound.hr"],
  "board"                 => ["damir.begovic@outwardbound.hr",
                              "gordan.budic@outwardbound.hr",
                              "roman@outwardbound.hr",
                              "vuk@outwardbound.hr"],
  "borna"                 => ["bornajelic@gmail.com"],
  "bozena"                => ["my.orange.vincent@gmail.com"],
  "branimir"              => ["producent@producent.hr"],
  "cedo"                  => ["cedo.josipovic@gmail.com"],
  "clanovi"               => ["members@outwardbound.hr"],
  "climbing"              => ["info@outwardbound.hr"],
  "contact"               => ["kontakt@outwardbound.hr"],
  "dado"                  => ["duda@outwardbound.hr",
                              "lovorka@outwardbound.hr",
                              "orsatk@yahoo.com"],
  "dalibor.obrovac"       => ["dalibor@outwardbound.hr"],
  "dalibor"               => ["d.obrovac@gmail.com"],
  "damir.begovic"         => ["damir.begovic1@zg.htnet.hr"],
  "darko.srut"            => ["darko@outwardbound.hr"],
  "darko"                 => ["darko.srut@gmail.com"],
  "dubravka.matic"        => ["dubravka21@gmail.com"],
  "dubravka.simunec"      => ["duda@outwardbound.hr"],
  "dubravka"              => ["d_u-d_a@hotmail.com"],
  "dubravka.glavor.rados" => ["dubravka.glavor.rados@gmail.com"],
  "duda"                  => ["d_u-d_a@hotmail.com"],
  "euprojekti"            => ["bozena@outwardbound.hr",
                              "branimir@outwardbound.hr",
                              "dado@outwardbound.hr",
                              "dubravka.matic@outwardbound.hr",
                              "filip@outwardbound.hr",
                              "jelena@outwardbound.hr",
                              "juraj@outwardbound.hr",
                              "maja@outwardbound.hr",
                              "marko@outwardbound.hr",
                              "matea@outwardbound.hr",
                              "sinisa@outwardbound.hr",
                              "tea@outwardbound.hr",
                              "vida@outwardbound.hr"],
  "filip"                 => ["filip.gospodnetic@gmail.com"],
  "gordan.budic"          => ["gordan.budic@gmail.com"],
  "gordan"                => ["gordan.budic@outwardbound.hr"],
  "gusteri"               => ["kandidati@outwardbound.hr"],
  "igor.parac"            => ["igor@outwardbound.hr"],
  "igor"                  => ["igparac@yahoo.com"],
  "info"                  => ["cedo@outwardbound.hr",
                              "dado@outwardbound.hr",
                              "darko@outwardbound.hr",
                              "duda@outwardbound.hr",
                              "juraj@outwardbound.hr",
                              "lovorka@outwardbound.hr",
                              "maja@outwardbound.hr",
                              "marko@outwardbound.hr",
                              "orsat@outwardbound.hr",
                              "sinisa@outwardbound.hr"],
  "insideout"             => ["cedo@outwardbound.hr",
                              "dado@outwardbound.hr",
                              "dubravka.matic@outwardbound.hr",
                              "juraj@outwardbound.hr",
                              "maja@outwardbound.hr",
                              "vida@outwardbound.hr"],
  "ivan.nosic"            => ["ivan@outwardbound.hr"],
  "ivan"                  => ["najcoolster@gmail.com"],
  "janko"                 => ["janko.marohnic@gmail.com"],
  "jelena"                => ["jeka.brezakova@gmail.com"],
  "jim"                   => ["james.s.bender@gmail.com"],
  "juraj.boljat"          => ["juraj@outwardbound.hr"],
  "juraj.brajnovic"       => ["jurko11@gmail.com"],
  "juraj"                 => ["juraj.boljat@gmail.com"],
  "kandidati"             => ["borna@outwardbound.hr",
                              "bozena@outwardbound.hr",
                              "branimir@outwardbound.hr",
                              "cedo@outwardbound.hr",
                              "dalibor@outwardbound.hr",
                              "dubravka.matic@outwardbound.hr",
                              "filip@outwardbound.hr",
                              "igor@outwardbound.hr",
                              "jelena@outwardbound.hr",
                              "juraj.brajnovic@outwardbound.hr",
                              "juraj@outwardbound.hr",
                              "maja@outwardbound.hr",
                              "marko@outwardbound.hr",
                              "matea@outwardbound.hr",
                              "sinisa@outwardbound.hr",
                              "tea@outwardbound.hr",
                              "tomislav@outwardbound.hr",
                              "tvrtko@outwardbound.hr",
                              "vida@outwardbound.hr"],
  "klub"                  => ["ana.armano@gmail.com",
                              "ana.katalinic@gmail.com",
                              "biljana@outwardbound.hr",
                              "brodic.luka@gmail.com",
                              "daenerysss@gmail.com",
                              "dohnjec@gmail.com",
                              "filip.bach@gmail.com",
                              "ivan@outwardbound.hr",
                              "laura@vmd.hr",
                              "marina@outwardbound.hr",
                              "snjezy@gmail.com",
                              "strumf54@yahoo.com",
                              "zeljka.zigic@yahoo.com"],
  "kontakt"               => ["info@outwardbound.hr"],
  "lovorka.simunec"       => ["lovorka@outwardbound.hr"],
  "lovorka"               => ["lovorkas@gmail.com"],
  "maja.priselac"         => ["majapr@outwardbound.hr"],
  "maja.skrljak"          => ["maja@outwardbound.hr"],
  "maja"                  => ["maja_skrljak@yahoo.com"],
  "majapr"                => ["maja.priselac@gmail.com"],
  "marina.brkic"          => ["marina@outwardbound.hr"],
  "marina"                => ["mbrkic99@gmail.com"],
  "marketing"             => ["branimir@outwardbound.hr",
                              "cedo@outwardbound.hr",
                              "dado@outwardbound.hr",
                              "dalibor@outwardbound.hr",
                              "dubravka.matic@outwardbound.hr",
                              "jelena@outwardbound.hr",
                              "juraj@outwardbound.hr",
                              "lovorka@outwardbound.hr",
                              "marko@outwardbound.hr",
                              "matea@outwardbound.hr",
                              "sinisa@outwardbound.hr",
                              "tea@outwardbound.hr",
                              "tomislav@outwardbound.hr",
                              "tvrtko@outwardbound.hr",
                              "vida@outwardbound.hr"],
  "marko"                 => ["marko.raduka@gmail.com"],
  "matea.brizic"          => ["matea@outwardbound.hr"],
  "matea"                 => ["matea3005@hotmail.com"],
  "members"               => ["staff@outwardbound.hr"],
  "operativa"             => ["info@outwardbound.hr"],
  "orsat.kratofil"        => ["orsat@outwardbound.hr"],
  "orsat"                 => ["orsatk@yahoo.com"],
  "osoblje"               => ["staff@outwardbound.hr"],
  "ozren.plese"           => ["ozren@outwardbound.hr"],
  "prijava"               => ["info@outwardbound.hr"],
  "roman.danko"           => ["roman@outwardbound.hr"],
  "roman"                 => ["romanco2cut@gmail.com"],
  "scuba"                 => ["info@outwardbound.hr"],
  "sinisa"                => ["sinisaskalec@hotmail.com"],
  "staff"                 => ["biljana@outwardbound.hr",
                              "borna@outwardbound.hr",
                              "branimir@outwardbound.hr",
                              "cedo@outwardbound.hr",
                              "dado@outwardbound.hr",
                              "dalibor@outwardbound.hr",
                              "darko@outwardbound.hr",
                              "dubravka.matic@outwardbound.hr",
                              "duda@outwardbound.hr",
                              "filip@outwardbound.hr",
                              "igor@outwardbound.hr",
                              "jelena@outwardbound.hr",
                              "juraj.brajnovic@outwardbound.hr",
                              "juraj@outwardbound.hr",
                              "lovorka@outwardbound.hr",
                              "maja@outwardbound.hr",
                              "majapr@outwardbound.hr",
                              "marko@outwardbound.hr",
                              "matea@outwardbound.hr",
                              "orsat@outwardbound.hr",
                              "ozren@outwardbound.hr",
                              "sinisa@outwardbound.hr",
                              "tea@outwardbound.hr",
                              "tihana@outwardbound.hr",
                              "tomislav@outwardbound.hr",
                              "tvrtko@outwardbound.hr",
                              "vida@outwardbound.hr"],
  "tea.djurek"            => ["tea@outwardbound.hr"],
  "tea"                   => ["tea.djurek@gmail.com"],
  "tihana.tamindzic"      => ["tihana@outwardbound.hr"],
  "tihana"                => ["tihanatosamja@gmail.com"],
  "tomislav.toric"        => ["tomislav@outwardbound.hr"],
  "tomislav"              => ["thetomi1@hotmail.com"],
  "trening"               => ["info@outwardbound.hr"],
  "tvrdi"                 => ["tvrtko@outwardbound.hr"],
  "tvrtko.dumancic"       => ["tvrtko@outwardbound.hr"],
  "tvrtko"                => ["tvrdi3@yahoo.com"],
  "twitter"               => ["dado@outwardbound.hr",
                              "janko.marohnic@gmail.com"],
  "vida"                  => ["vidaungar@yahoo.com"],
  "visina"                => ["prijava@outwardbound.hr"],
  "vladimir.mesaric"      => ["dado@outwardbound.hr"],
  "vuk"                   => ["vuk@mayo.edu"],
}
