EMAILS = {
  "aco@outwardbound.hr"              => ["aleksakocijan@yahoo.com"],
  "aleksa.kocijan@outwardbound.hr"   => ["aco@outwardbound.hr"],
  "apply@outwardbound.hr"            => ["prijava@outwardbound.hr"],
  "biljana.bekic@outwardbound.hr"    => ["biljana@outwardbound.hr"],
  "board@outwardbound.hr"            => ["damir.begovic@outwardbound.hr",
                                         "gordan.budic@outwardbound.hr",
                                         "roman@outwardbound.hr",
                                         "vuk@outwardbound.hr"],
  "borna@outwardbound.hr"            => ["bornajelic@gmail.com"],
  "bozena@outwardbound.hr"           => ["my.orange.vincent@gmail.com"],
  "branimir@outwardbound.hr"         => ["producent@producent.hr"],
  "cedo@outwardbound.hr"             => ["cedo.josipovic@gmail.com"],
  "clanovi@outwardbound.hr"          => ["members@outwardbound.hr"],
  "climbing@outwardbound.hr"         => ["info@outwardbound.hr"],
  "contact@outwardbound.hr"          => ["kontakt@outwardbound.hr"],
  "dado@outwardbound.hr"             => ["duda@outwardbound.hr",
                                         "lovorka@outwardbound.hr",
                                         "orsatk@yahoo.com"],
  "dalibor.obrovac@outwardbound.hr"  => ["dalibor@outwardbound.hr"],
  "dalibor@outwardbound.hr"          => ["d.obrovac@gmail.com"],
  "damir.begovic@outwardbound.hr"    => ["damir.begovic1@zg.htnet.hr"],
  "darko.srut@outwardbound.hr"       => ["darko@outwardbound.hr"],
  "darko@outwardbound.hr"            => ["darko.srut@gmail.com"],
  "dubravka.matic@outwardbound.hr"   => ["dubravka21@gmail.com"],
  "dubravka.simunec@outwardbound.hr" => ["duda@outwardbound.hr"],
  "dubravka@outwardbound.hr"         => ["d_u-d_a@hotmail.com"],
  "duda@outwardbound.hr"             => ["d_u-d_a@hotmail.com"],
  "euprojekti@outwardbound.hr"       => ["bozena@outwardbound.hr",
                                         "branimir@outwardbound.hr",
                                         "dado@outwardbound.hr",
                                         "dubravka.matic@outwardbound.hr",
                                         "filip@outwardbound.hr",
                                         "jelena@outwardbound.hr",
                                         "juraj@outwardbound.hr",
                                         "maja@outwardbound.hr",
                                         "marko@outwardbound.hr",
                                         "matea@outwardbound.hr",
                                         "sinisa@outwardbound.hr",
                                         "tea@outwardbound.hr",
                                         "vida@outwardbound.hr"],
  "filip@outwardbound.hr"            => ["filip.gospodnetic@gmail.com"],
  "gordan.budic@outwardbound.hr"     => ["gordan.budic@gmail.com"],
  "gordan@outwardbound.hr"           => ["gordan.budic@outwardbound.hr"],
  "gusteri@outwardbound.hr"          => ["kandidati@outwardbound.hr"],
  "igor.parac@outwardbound.hr"       => ["igor@outwardbound.hr"],
  "igor@outwardbound.hr"             => ["igparac@yahoo.com"],
  "info@outwardbound.hr"             => ["cedo@outwardbound.hr",
                                         "dado@outwardbound.hr",
                                         "darko@outwardbound.hr",
                                         "duda@outwardbound.hr",
                                         "juraj@outwardbound.hr",
                                         "lovorka@outwardbound.hr",
                                         "maja@outwardbound.hr",
                                         "marko@outwardbound.hr",
                                         "orsat@outwardbound.hr",
                                         "sinisa@outwardbound.hr"],
  "insideout@outwardbound.hr"        => ["cedo@outwardbound.hr",
                                         "dado@outwardbound.hr",
                                         "dubravka.matic@outwardbound.hr",
                                         "juraj@outwardbound.hr",
                                         "maja@outwardbound.hr",
                                         "vida@outwardbound.hr"],
  "ivan.nosic@outwardbound.hr"       => ["ivan@outwardbound.hr"],
  "ivan@outwardbound.hr"             => ["najcoolster@gmail.com"],
  "janko@outwardbound.hr"            => ["janko.marohnic@gmail.com"],
  "jelena@outwardbound.hr"           => ["jeka.brezakova@gmail.com"],
  "jim@outwardbound.hr"              => ["james.s.bender@gmail.com"],
  "juraj.boljat@outwardbound.hr"     => ["juraj@outwardbound.hr"],
  "juraj.brajnovic@outwardbound.hr"  => ["jurko11@gmail.com"],
  "juraj@outwardbound.hr"            => ["juraj.boljat@gmail.com"],
  "kandidati@outwardbound.hr"        => ["borna@outwardbound.hr",
                                         "bozena@outwardbound.hr",
                                         "branimir@outwardbound.hr",
                                         "cedo@outwardbound.hr",
                                         "dalibor@outwardbound.hr",
                                         "dubravka.matic@outwardbound.hr",
                                         "filip@outwardbound.hr",
                                         "igor@outwardbound.hr",
                                         "jelena@outwardbound.hr",
                                         "juraj.brajnovic@outwardbound.hr",
                                         "juraj@outwardbound.hr",
                                         "maja@outwardbound.hr",
                                         "marko@outwardbound.hr",
                                         "matea@outwardbound.hr",
                                         "sinisa@outwardbound.hr",
                                         "tea@outwardbound.hr",
                                         "tomislav@outwardbound.hr",
                                         "tvrtko@outwardbound.hr",
                                         "vida@outwardbound.hr"],
  "klub@outwardbound.hr"             => ["ana.armano@gmail.com",
                                         "ana.katalinic@gmail.com",
                                         "biljana@outwardbound.hr",
                                         "brodic.luka@gmail.com",
                                         "daenerysss@gmail.com",
                                         "dohnjec@gmail.com",
                                         "filip.bach@gmail.com",
                                         "ivan@outwardbound.hr",
                                         "laura@vmd.hr",
                                         "marina@outwardbound.hr",
                                         "snjezy@gmail.com",
                                         "strumf54@yahoo.com",
                                         "zeljka.zigic@yahoo.com"],
  "kontakt@outwardbound.hr"          => ["info@outwardbound.hr"],
  "lovorka.simunec@outwardbound.hr"  => ["lovorka@outwardbound.hr"],
  "lovorka@outwardbound.hr"          => ["lovorkas@gmail.com"],
  "maja.priselac@outwardbound.hr"    => ["majapr@outwardbound.hr"],
  "maja.skrljak@outwardbound.hr"     => ["maja@outwardbound.hr"],
  "maja@outwardbound.hr"             => ["maja_skrljak@yahoo.com"],
  "majapr@outwardbound.hr"           => ["maja.priselac@gmail.com"],
  "marina.brkic@outwardbound.hr"     => ["marina@outwardbound.hr"],
  "marina@outwardbound.hr"           => ["mbrkic99@gmail.com"],
  "marketing@outwardbound.hr"        => ["branimir@outwardbound.hr",
                                         "cedo@outwardbound.hr",
                                         "dado@outwardbound.hr",
                                         "dalibor@outwardbound.hr",
                                         "dubravka.matic@outwardbound.hr",
                                         "jelena@outwardbound.hr",
                                         "juraj@outwardbound.hr",
                                         "lovorka@outwardbound.hr",
                                         "marko@outwardbound.hr",
                                         "matea@outwardbound.hr",
                                         "sinisa@outwardbound.hr",
                                         "tea@outwardbound.hr",
                                         "tomislav@outwardbound.hr",
                                         "tvrtko@outwardbound.hr",
                                         "vida@outwardbound.hr"],
  "marko@outwardbound.hr"            => ["marko.raduka@gmail.com"],
  "matea.brizic@outwardbound.hr"     => ["matea@outwardbound.hr"],
  "matea@outwardbound.hr"            => ["matea3005@hotmail.com"],
  "members@outwardbound.hr"          => ["staff@outwardbound.hr"],
  "operativa@outwardbound.hr"        => ["info@outwardbound.hr"],
  "orsat.kratofil@outwardbound.hr"   => ["orsat@outwardbound.hr"],
  "orsat@outwardbound.hr"            => ["orsatk@yahoo.com"],
  "osoblje@outwardbound.hr"          => ["staff@outwardbound.hr"],
  "ozren.plese@outwardbound.hr"      => ["ozren@outwardbound.hr"],
  "prijava@outwardbound.hr"          => ["info@outwardbound.hr"],
  "roman.danko@outwardbound.hr"      => ["roman@outwardbound.hr"],
  "roman@outwardbound.hr"            => ["romanco2cut@gmail.com"],
  "scuba@outwardbound.hr"            => ["info@outwardbound.hr"],
  "sinisa@outwardbound.hr"           => ["sinisaskalec@hotmail.com"],
  "staff@outwardbound.hr"            => ["biljana@outwardbound.hr",
                                         "borna@outwardbound.hr",
                                         "branimir@outwardbound.hr",
                                         "cedo@outwardbound.hr",
                                         "dado@outwardbound.hr",
                                         "dalibor@outwardbound.hr",
                                         "darko@outwardbound.hr",
                                         "dubravka.matic@outwardbound.hr",
                                         "duda@outwardbound.hr",
                                         "filip@outwardbound.hr",
                                         "igor@outwardbound.hr",
                                         "jelena@outwardbound.hr",
                                         "juraj.brajnovic@outwardbound.hr",
                                         "juraj@outwardbound.hr",
                                         "lovorka@outwardbound.hr",
                                         "maja@outwardbound.hr",
                                         "majapr@outwardbound.hr",
                                         "marko@outwardbound.hr",
                                         "matea@outwardbound.hr",
                                         "orsat@outwardbound.hr",
                                         "ozren@outwardbound.hr",
                                         "sinisa@outwardbound.hr",
                                         "tea@outwardbound.hr",
                                         "tihana@outwardbound.hr",
                                         "tomislav@outwardbound.hr",
                                         "tvrtko@outwardbound.hr",
                                         "vida@outwardbound.hr"],
  "tea.djurek@outwardbound.hr"       => ["tea@outwardbound.hr"],
  "tea@outwardbound.hr"              => ["tea.djurek@gmail.com"],
  "tihana.tamindzic@outwardbound.hr" => ["tihana@outwardbound.hr"],
  "tihana@outwardbound.hr"           => ["tihanatosamja@gmail.com"],
  "tomislav.toric@outwardbound.hr"   => ["tomislav@outwardbound.hr"],
  "tomislav@outwardbound.hr"         => ["thetomi1@hotmail.com"],
  "trening@outwardbound.hr"          => ["info@outwardbound.hr"],
  "tvrdi@outwardbound.hr"            => ["tvrtko@outwardbound.hr"],
  "tvrtko.dumancic@outwardbound.hr"  => ["tvrtko@outwardbound.hr"],
  "tvrtko@outwardbound.hr"           => ["tvrdi3@yahoo.com"],
  "twitter@outwardbound.hr"          => ["dado@outwardbound.hr",
                                         "janko.marohnic@gmail.com"],
  "vida@outwardbound.hr"             => ["vidaungar@yahoo.com"],
  "visina@outwardbound.hr"           => ["prijava@outwardbound.hr"],
  "vladimir.mesaric@outwardbound.hr" => ["dado@outwardbound.hr"],
  "vuk@outwardbound.hr"              => ["vuk@mayo.edu"],
}
