defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning

development:
  <<: *defaults
  database: outward-bound_development

test: &test
  <<: *defaults
  database: outward-bound_test

production:
  <<: *defaults
  database: outward-bound_production

cucumber:
  <<: *test
